Repository jenkinsci/coverage-model, pull requests merged in 2024-01, with the labels that each got.

#66 [JENKINS-72449] Add a toggle to ignore empty results
  src/main/java/edu/hm/hafner/coverage/CoverageParser.java
  src/main/java/edu/hm/hafner/coverage/parser/CoberturaParser.java
  src/main/java/edu/hm/hafner/coverage/parser/JacocoParser.java
  src/main/java/edu/hm/hafner/coverage/parser/JunitParser.java
  src/main/java/edu/hm/hafner/coverage/parser/PitestParser.java
  src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java
  src/test/java/edu/hm/hafner/coverage/parser/CoberturaParserTest.java
  src/test/java/edu/hm/hafner/coverage/parser/JacocoParserTest.java
  src/test/java/edu/hm/hafner/coverage/parser/JunitParserTest.java
  src/test/java/edu/hm/hafner/coverage/parser/PitestParserTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/cobertura/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/jacoco/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/junit/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/pit/empty.xml
Labels: enhancement

#64 Add support for OpenCover format
  src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java
  src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/coverage/parser/OpenCoverParserTest.java
  src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-empty-module.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-missing-module-name.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-missing-source-line.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-reporttotestsourcefiles.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-withskippedmodules.xml
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover.xml
Labels: feature

#68 Add the test-strength metric for PIT results
  src/main/java/edu/hm/hafner/coverage/Metric.java
  src/main/java/edu/hm/hafner/coverage/Mutation.java
  src/main/java/edu/hm/hafner/coverage/MutationStatus.java
  src/main/java/edu/hm/hafner/coverage/Value.java
  src/test/java/edu/hm/hafner/coverage/parser/PitestParserTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/pit/mutations-with-timeout.xml
Labels: enhancement

#69 Add support for NUnit format
  src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java
  src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/coverage/parser/NunitParserTest.java
  src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-invalid-status.xml
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-no-failure-block.xml
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit-no-message.xml
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit.xml
  src/test/resources/edu/hm/hafner/coverage/parser/nunit/nunit2-format.xml
Labels: feature

#70 Extract a common base class for test parsers
  src/main/java/edu/hm/hafner/coverage/CoverageParser.java
  src/main/java/edu/hm/hafner/coverage/parser/AbstractTestParser.java
  src/main/java/edu/hm/hafner/coverage/parser/JunitParser.java
  src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java
  src/main/java/edu/hm/hafner/coverage/parser/OpenCoverParser.java
  src/test/java/edu/hm/hafner/coverage/parser/AbstractParserTest.java
  src/test/java/edu/hm/hafner/coverage/parser/OpenCoverParserTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/opencover/opencover-with-bom.xml
Labels: internal

#72 Add support for XUnit .NET format
  README.md
  src/main/java/edu/hm/hafner/coverage/parser/XunitParser.java
  src/main/java/edu/hm/hafner/coverage/registry/ParserRegistry.java
  src/test/java/edu/hm/hafner/coverage/parser/XunitParserTest.java
  src/test/java/edu/hm/hafner/coverage/registry/ParserRegistryTest.java
  src/test/resources/edu/hm/hafner/coverage/parser/xunit/empty.xml
  src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-invalid-status.xml
  src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-no-failure-block.xml
  src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit-no-message.xml
  src/test/resources/edu/hm/hafner/coverage/parser/xunit/xunit.xml
Labels: enhancement
